### ISSUE TITLE
Using condition = NULL in multiple.netfacs()

### ISSUE THREAD

**Issue by avrincon** [NetFACS/NetFACS#3]
multiple.netfacs() currently does not compute permutations when condition = NULL. It is unclear whether this behavior would be useful since the aim is to compare conditions against each other.

data(emotions_set)
emo.faces <- multiple.netfacs(
  data = emotions_set[[1]],
  condition = NULL,
  ran.trials = 10
)

**Comment by AlexMielke1988** [comment]
This was intentional, because if no condition is specified, there is just one possible network currently.

**Comment by avrincon** [comment]
Yeah, if it's intentional then I would update the documentation and include appropriate error/warning messages.

Although, I imagined a scenario where someone would supply a condition vector and compare each condition to a randomized null, rather than to bootstraps of the other conditions. But again, not sure if it's useful to implement that in multiple.netfacs().
