### ISSUE TITLE
Issue with "control" argument

### ISSUE THREAD

**Issue by JanaMuschinski** [NetFACS/NetFACS#6]
Hi NetFACS team,

I've been playing around with the control argument and noticed two things. 

1) If the user fails to set the control as a factor, the control variable may not work (based on the fact that it doesn't throw an error, even though it does when set as a factor, and the results with my own data don't change *at all* if I set a control variable or not). If this is the case, it might be worth having a safeguard for scenarios where people forget to set it as a factor - either a warning or for it to be automatically changed to a factor.

2)  When it is set as a factor, the netfacs function throws the following error, even if cases of the control variable are evenly spread through the test condition and null condition:

Warning message:
In netfacs(data = au.data, condition = au.info.factor$emotion, test.condition = "anger",  :
  The following control values are present in null.condition but not test.condition: 0. These observations will be ignored during the bootstrapping procedure.

When you look at a table of category by condition below, both categories (0 and 1) are spread across all conditions. 

Example:
```
set.seed(1)


au.data <- emotions_set[[1]]
# this is the basic data frame, with each video represented by a row, and each Action Unit represented by a column

au.info <- emotions_set[[2]]
# this is the additional information about the emotions etc

# We remove AU 25 here, because it is not informative, and all AUs that have 2 or fewer occurrences, because not meaningful interpretation is available for them
au.data <- au.data[, setdiff(colnames(au.data), "25")]
au.data <- au.data[, colSums(au.data) > 2]

au.info$category <- rbinom(n=327,size=1,prob=0.5)

au.info.factor <- au.info  %>%
  mutate(category = as.factor(category))

set.seed(1)

angry.face <- netfacs(
  data = au.data, # this is the data matrix
  condition = au.info$emotion, # info about condition of each case
  test.condition = "anger", # condition we are interested in
  null.condition = NULL, # null condition (test against all other emotions)
  duration = NULL, # we could add duration information for videos
  ran.trials = 1000, # number of randomizations. The larger the better
  control = list(au.info$category), # control variables, e.g. gender, ethnicity etc.
  random.level = NULL, # Works like a random effect.
  combination.size = 4, # limit the analysis to make things faster,
  tail = "upper.tail", # should the p-value reflect two-tailed or right/left tailed testing?
  use_parallel = TRUE, # use parallel processing
  n_cores = NULL # number of cores for parallel processing
)

# no error message if run with au.info$category
# now swap to using the au.info.factor dataset and you get an error

set.seed(1)


angry.face.factor <- netfacs(
  data = au.data, # this is the data matrix
  condition = au.info.factor$emotion, # info about condition of each case
  test.condition = "anger", # condition we are interested in
  null.condition = NULL, # null condition (test against all other emotions)
  duration = NULL, # we could add duration information for videos
  ran.trials = 1000, # number of randomizations. The larger the better
  control = list(au.info.factor$category), # control variables, e.g. gender, ethnicity etc.
  random.level = NULL, # Works like a random effect.
  combination.size = 4, # limit the analysis to make things faster,
  tail = "upper.tail", # should the p-value reflect two-tailed or right/left tailed testing?
  use_parallel = TRUE, # use parallel processing
  n_cores = NULL # number of cores for parallel processing
)



table(au.info$emotion, au.info$category)
# can see that the two categories are spread pretty evenly across conditions. Control "0" certainly does show up in both the test condition (angry faces) and the control cases.

netfacs_extract(angry.face)
netfacs_extract(angry.face.factor)
# results do appear different depending on whether I run it with the control variable as a factor or not
```

**Comment by JanaMuschinski** [comment]
So based on the "used.data" object in the output, the control is used when the variable is in the form of an integer or character, but actually not when in the form of a factor. The results still don't seem to change though even with it listing the control variable properly? 

ETA: Of course with the random assignment in the above example you wouldn't really expect any big changes, but with my own data, where it would be quite likely that there would be at least some minor differences, there seems to be no change when I run with control variables versus without.

**Comment by avrincon** [comment]
Hi Jana,

You're right that the control argument is not handling when the variable is a factor correctly. I'll try to fix that on the next patch. 

If passed on a a character variable, the control seems to be working correctly. All the control variable does is give weight to how likely an observation (row) is to be chosen during the bootstrapping procedure. The more balanced the control variable is, the less of an effect it will have on results. In your example, the observations assigned category=0 and category=1 both had near 50% chance of being chosen (i.e. there was no difference between them) so we would not expect results to differ with or without the control variable. 

A scenario where it might make a difference is if, for example, you wanted to compare angry (test condition) and happy faces (null condition). But in the data 80% of angry faces were from males, but only 30% of happy faces were from males. If you added a control variable of sex (male/female), this would ensure that the bootstrapped sample of happy faces were also 80% from males (to match the test condition) as compared to 30% if it was random. If, on the other hand, in the data 80% of happy faces were also from males, then adding sex as a control variable would actually make no difference. Finally, if there are no differences in the angry and happy faces of males and females, then of course adding sex as a control variable would still not make a difference to results regardless of how balanced the ratio of males to females in the data is.

I hope that makes sense, and perhaps it explains why the control variable is not making a difference in your data either.

**Comment by JanaMuschinski** [comment]
Thanks so much for the response and explanation! Glad that I was right that something seemed to be working wrong with the factor version. 

The explanation of how the control variable makes sense - yeah my example was not great given I would have to change the proportion of male/female by category to make it potentially meaningful! Glad to hear it is working correctly, my original dataset I think is quite balanced so it must have just been balanced enough to not make a noticeable difference!

Thanks for the help!
